title: Logic Colloquium 2024
preposition: at
description: >-
  European Summer Meeting of the Association for Symbolic Logic, Gothenburg, Sweden
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lc2024.se" # the base hostname & protocol for your site, e.g. https://example.com

# theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  - bundle
  - CT_data/

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  #
  email: mailto:info@lc2024.se

  # Show theme errors:
  show_errors: True

  # Nav-stuff moved to data/navigation.yml

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: 'LCLogo.svg'
    links:
      - name: Register
        relative_url: /registration/
      - name: Contribute a talk
        relative_url: /contributed_talks/
      - name: Apply for travel support
        relative_url: /travel_grants/
      - name: Contact us
        absolute_url: 'mailto:info@lc2024.se'
    #     absolute_url: ''

  # Information boxes
  info_bars:
    # - title: Under construction!
    #   color: warning
    #   text: |
    #     This page is currently under construction. Watch your head!

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: false
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: "57.69437, 11.98497"
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 19

  map-banquet:
    # Initial map center point
    home_coord: "57.69509, 11.99604"
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 19

  talks:
    # Talk categories
    main_categories:
      - name: Plenary Talk
        color: plenary
      - name: Tutorial
        color: tutorial
      - name: Special Session
        color: special
      - name: Contributed Talk
        color: talk
      - name: Opening
        color: plenary
        hide: true
        drop: true
      - name: Social
        color: social
        drop: true

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/schedule'

    # Time steps in program table
    time_steps: 10 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false

